project_id = "mfaxpkfpackofxklccyl"

[functions.arquivar-mensagens-antigas]
verify_jwt = false

[functions.consolidar-uso-diario]
verify_jwt = false

[functions.processar-followups-agendados]
verify_jwt = false
